/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AmbulanceId = Principal;
export interface AmbulanceLocation {
  'ambulanceId' : AmbulanceId,
  'timestamp' : Time,
  'coordinates' : Coordinates,
}
export type AppRole = { 'ambulance' : null } |
  { 'police' : null };
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface SOSAlert {
  'active' : boolean,
  'ambulanceId' : AmbulanceId,
  'timestamp' : Time,
  'coordinates' : Coordinates,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : AppRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateSOS' : ActorMethod<[], undefined>,
  'deleteAmbulanceLocation' : ActorMethod<[AmbulanceId], undefined>,
  'getActiveSOSAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getAllLocations' : ActorMethod<[], Array<AmbulanceLocation>>,
  'getAllSOSAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getAmbulanceLocation' : ActorMethod<[AmbulanceId], [] | [AmbulanceLocation]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLocationsCountInRadius' : ActorMethod<[Coordinates, number], bigint>,
  'getLocationsInRadius' : ActorMethod<
    [Coordinates, number],
    Array<AmbulanceLocation>
  >,
  'getLocationsInTimeRange' : ActorMethod<
    [bigint, bigint],
    Array<AmbulanceLocation>
  >,
  'getSOSAlert' : ActorMethod<[AmbulanceId], [] | [SOSAlert]>,
  'getSortedLocationsInRadius' : ActorMethod<
    [Coordinates, number],
    Array<AmbulanceLocation>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'triggerSOS' : ActorMethod<[Coordinates], undefined>,
  'updateAmbulanceLocation' : ActorMethod<[Coordinates], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];