/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AmbulanceId = IDL.Principal;
export const Time = IDL.Int;
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SOSAlert = IDL.Record({
  'active' : IDL.Bool,
  'ambulanceId' : AmbulanceId,
  'timestamp' : Time,
  'coordinates' : Coordinates,
});
export const AmbulanceLocation = IDL.Record({
  'ambulanceId' : AmbulanceId,
  'timestamp' : Time,
  'coordinates' : Coordinates,
});
export const AppRole = IDL.Variant({
  'ambulance' : IDL.Null,
  'police' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateSOS' : IDL.Func([], [], []),
  'deleteAmbulanceLocation' : IDL.Func([AmbulanceId], [], []),
  'getActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getAllLocations' : IDL.Func([], [IDL.Vec(AmbulanceLocation)], ['query']),
  'getAllSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getAmbulanceLocation' : IDL.Func(
      [AmbulanceId],
      [IDL.Opt(AmbulanceLocation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocationsCountInRadius' : IDL.Func(
      [Coordinates, IDL.Float64],
      [IDL.Nat],
      ['query'],
    ),
  'getLocationsInRadius' : IDL.Func(
      [Coordinates, IDL.Float64],
      [IDL.Vec(AmbulanceLocation)],
      ['query'],
    ),
  'getLocationsInTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(AmbulanceLocation)],
      ['query'],
    ),
  'getSOSAlert' : IDL.Func([AmbulanceId], [IDL.Opt(SOSAlert)], ['query']),
  'getSortedLocationsInRadius' : IDL.Func(
      [Coordinates, IDL.Float64],
      [IDL.Vec(AmbulanceLocation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'triggerSOS' : IDL.Func([Coordinates], [], []),
  'updateAmbulanceLocation' : IDL.Func([Coordinates], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AmbulanceId = IDL.Principal;
  const Time = IDL.Int;
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SOSAlert = IDL.Record({
    'active' : IDL.Bool,
    'ambulanceId' : AmbulanceId,
    'timestamp' : Time,
    'coordinates' : Coordinates,
  });
  const AmbulanceLocation = IDL.Record({
    'ambulanceId' : AmbulanceId,
    'timestamp' : Time,
    'coordinates' : Coordinates,
  });
  const AppRole = IDL.Variant({ 'ambulance' : IDL.Null, 'police' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateSOS' : IDL.Func([], [], []),
    'deleteAmbulanceLocation' : IDL.Func([AmbulanceId], [], []),
    'getActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getAllLocations' : IDL.Func([], [IDL.Vec(AmbulanceLocation)], ['query']),
    'getAllSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getAmbulanceLocation' : IDL.Func(
        [AmbulanceId],
        [IDL.Opt(AmbulanceLocation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocationsCountInRadius' : IDL.Func(
        [Coordinates, IDL.Float64],
        [IDL.Nat],
        ['query'],
      ),
    'getLocationsInRadius' : IDL.Func(
        [Coordinates, IDL.Float64],
        [IDL.Vec(AmbulanceLocation)],
        ['query'],
      ),
    'getLocationsInTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(AmbulanceLocation)],
        ['query'],
      ),
    'getSOSAlert' : IDL.Func([AmbulanceId], [IDL.Opt(SOSAlert)], ['query']),
    'getSortedLocationsInRadius' : IDL.Func(
        [Coordinates, IDL.Float64],
        [IDL.Vec(AmbulanceLocation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'triggerSOS' : IDL.Func([Coordinates], [], []),
    'updateAmbulanceLocation' : IDL.Func([Coordinates], [], []),
  });
};

export const init = ({ IDL }) => { return []; };